### ISSUE TITLE
`worker.init` is not a function

### ISSUE THREAD

**Issue by 0xAndrewBlack** [brussell98/megane#4]
![image](https://user-images.githubusercontent.com/50300348/202281388-5cf1b13f-b77c-47c7-be0d-9633879b0369.png)

Hello im looking for help with this package I added a screenshot, what could cause this error?

**Comment by brussell98** [comment]
You're not extending `BaseClusterWorker`

**Comment by 0xAndrewBlack** [comment]
and indeed it was thanks for the reply btw.
I managed to get it working and it's fantastic.
